# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      # Invoke-Lint returns result output and writes exceptions to the Warning stream.
      #   It throws no exceptions and returns no exit codes.
      #   Convert the reported count as the exit code for pre-commit.
      - id: invoke-lint
        name: invoke-lint
        alias: Invoke-Lint
        entry: pwsh -NoLogo -NoProfile -NonInteractive -Command "Write-Output ($Report=Invoke-Lint); exit $Report.Count"
        files: '.*\.ps(d|m)?1'
        language: system
        pass_filenames: false

      # Invoke-Test returns result output and writes exceptions to the Warning stream.
      #   It ignores Pester exceptions and exit code workflows to control the workflow.
      #   It throws no exceptions and returns no exit codes.
      #   Return the $LASTEXITCODE set by Pester for pre-commit.
      - id: invoke-test
        name: invoke-test
        alias: Invoke-Test
        entry: pwsh -NoLogo -NoProfile -NonInteractive -Command "Invoke-Test; exit $LASTEXITCODE"
        files: '.*\.ps(d|m)?1'
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace
